<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\..\Libs\KXMapStudio.Libs\KXMapStudio.Libs.csproj"/>
	</ItemGroup>
	
	<ItemGroup>
		<Resource Include="KXMapStudio.ico">
			<Link>Resources\KXMapStudio.ico</Link>
		</Resource>
	</ItemGroup>
	
	<ItemGroup>
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
	<ItemGroup>
		<Page Update="Views\Windows\WorkspaceWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
			<XamlRuntime>Wpf</XamlRuntime>
			<SubType>Designer</SubType>
		</Page>
	</ItemGroup>

</Project>
